export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  type: "Full-time" | "Part-time" | "Contract" | "Freelance" | "Internship";
  category: string;
  collar: "white" | "blue";
  salary: string;
  posted: string;
  logo: string;
  featured?: boolean;
  remote?: boolean;
  urgent?: boolean;
  description: string;
  tags: string[];
  applyUrl: string;
  requirements?: string[];
  benefits?: string[];
}

export const jobCategories = [
  { name: "Technology", icon: "💻", count: 2840, color: "primary" },
  { name: "Healthcare", icon: "🏥", count: 1920, color: "accent" },
  { name: "Finance", icon: "💰", count: 1560, color: "highlight" },
  { name: "Construction", icon: "🏗️", count: 1340, color: "primary" },
  { name: "Education", icon: "📚", count: 980, color: "accent" },
  { name: "Marketing", icon: "📢", count: 870, color: "highlight" },
  { name: "Manufacturing", icon: "🏭", count: 760, color: "primary" },
  { name: "Transportation", icon: "🚛", count: 650, color: "accent" },
  { name: "Hospitality", icon: "🏨", count: 590, color: "highlight" },
  { name: "Retail", icon: "🛒", count: 1200, color: "primary" },
  { name: "Engineering", icon: "⚙️", count: 1100, color: "accent" },
  { name: "Legal", icon: "⚖️", count: 430, color: "highlight" },
];

export const featuredJobs: Job[] = [
  // === UGANDA ===
  {
    id: "ug-1",
    title: "Senior Software Engineer",
    company: "Andela Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "UGX 8M – 15M/mo",
    posted: "2 hours ago",
    logo: "🟣",
    featured: true,
    remote: true,
    description: "Build scalable web applications using React, Node.js, and cloud services for international clients. Collaborate with distributed teams across Africa and North America.",
    tags: ["React", "Node.js", "AWS"],
    applyUrl: "https://andela.com/careers",
    requirements: ["5+ years experience in full-stack development", "Proficiency in React, Node.js, TypeScript", "Experience with AWS or GCP", "Strong communication skills"],
    benefits: ["Remote work flexibility", "Health insurance", "Learning & development budget", "Stock options"],
  },
  {
    id: "ug-2",
    title: "Electrician – Commercial",
    company: "Umeme Limited",
    location: "Jinja, Uganda",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "UGX 1.5M – 3M/mo",
    posted: "4 hours ago",
    logo: "🔵",
    urgent: true,
    description: "Install, maintain, and repair electrical systems in commercial buildings and industrial facilities across Eastern Uganda.",
    tags: ["Electrical", "Commercial", "Licensed"],
    applyUrl: "https://www.umeme.co.ug/careers",
    requirements: ["Valid electrician license", "3+ years commercial experience", "Knowledge of electrical codes", "Ability to read blueprints"],
    benefits: ["Competitive salary", "On-site training", "Safety equipment provided"],
  },
  {
    id: "ug-3",
    title: "Registered Nurse – ICU",
    company: "Mulago National Referral Hospital",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "UGX 2.5M – 5M/mo",
    posted: "6 hours ago",
    logo: "🟢",
    urgent: true,
    description: "Provide critical patient care in the Intensive Care Unit. Must have BSN and at least 2 years ICU experience.",
    tags: ["Nursing", "ICU", "BSN Required"],
    applyUrl: "https://www.health.go.ug/jobs",
    requirements: ["BSN degree", "2+ years ICU experience", "Valid nursing license", "BLS/ACLS certification"],
    benefits: ["Government pension", "Medical cover", "Professional development"],
  },
  {
    id: "ug-4",
    title: "Plumber – Residential & Industrial",
    company: "National Water & Sewerage Corporation",
    location: "Entebbe, Uganda",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "UGX 1.2M – 2.5M/mo",
    posted: "8 hours ago",
    logo: "🔵",
    description: "Handle residential and industrial plumbing installations, water system repairs, and preventive maintenance contracts.",
    tags: ["Plumbing", "Water Systems", "Maintenance"],
    applyUrl: "https://www.nwsc.co.ug/careers",
    requirements: ["Plumbing certification", "Experience with industrial systems", "Valid driver's license"],
  },
  {
    id: "ug-5",
    title: "Financial Analyst",
    company: "Stanbic Bank Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Finance",
    collar: "white",
    salary: "UGX 5M – 9M/mo",
    posted: "1 day ago",
    logo: "🟡",
    featured: true,
    description: "Perform financial modeling, risk analysis, and investment advisory for corporate and institutional clients.",
    tags: ["Finance", "Risk Analysis", "Excel"],
    applyUrl: "https://www.stanbicbank.co.ug/uganda/careers",
    requirements: ["Degree in Finance/Accounting", "CFA or CPA preferred", "3+ years in financial analysis", "Advanced Excel skills"],
    benefits: ["Performance bonus", "Health & life insurance", "Pension scheme", "Training opportunities"],
  },
  {
    id: "ug-6",
    title: "Welder – MIG/TIG Specialist",
    company: "Roofings Group",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "UGX 1.5M – 3M/mo",
    posted: "1 day ago",
    logo: "🔴",
    urgent: true,
    description: "Perform MIG and TIG welding on structural steel for construction projects. Must read blueprints and weld to code specifications.",
    tags: ["MIG Welding", "TIG", "Structural Steel"],
    applyUrl: "https://www.roofings.co.ug/careers",
    requirements: ["Welding certification", "Experience with MIG/TIG", "Blueprint reading ability"],
  },
  {
    id: "ug-7",
    title: "Marketing Manager",
    company: "MTN Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Marketing",
    collar: "white",
    salary: "UGX 6M – 12M/mo",
    posted: "3 hours ago",
    logo: "🟡",
    featured: true,
    description: "Lead brand campaigns, digital marketing strategy, and customer acquisition initiatives for Uganda's largest telecom.",
    tags: ["Digital Marketing", "Brand Strategy", "Telecoms"],
    applyUrl: "https://www.mtn.co.ug/careers",
    requirements: ["5+ years marketing experience", "Degree in Marketing/Business", "Digital marketing expertise", "Team leadership skills"],
    benefits: ["Airtime & data allowance", "Health insurance", "Performance bonus", "Company car"],
  },
  {
    id: "ug-8",
    title: "Heavy Equipment Operator",
    company: "CICO Construction Uganda",
    location: "Mbale, Uganda",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "UGX 2M – 4M/mo",
    posted: "5 hours ago",
    logo: "🟠",
    description: "Operate excavators, bulldozers, and graders for road construction projects in Eastern Uganda.",
    tags: ["Excavator", "Road Construction", "CDL"],
    applyUrl: "https://www.brightermonday.co.ug/jobs",
  },
  {
    id: "ug-9",
    title: "Accountant",
    company: "Deloitte Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Finance",
    collar: "white",
    salary: "UGX 4M – 8M/mo",
    posted: "2 days ago",
    logo: "🟢",
    description: "Manage auditing engagements, prepare financial statements, and ensure compliance with IFRS standards.",
    tags: ["CPA", "Auditing", "IFRS"],
    applyUrl: "https://www2.deloitte.com/ug/en/careers.html",
    requirements: ["CPA qualification", "Degree in Accounting", "2+ years audit experience", "IFRS knowledge"],
    benefits: ["Global career opportunities", "Professional development", "Health insurance", "Annual bonus"],
  },
  {
    id: "ug-10",
    title: "Hotel Chef – Sous Chef",
    company: "Serena Hotel Kampala",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Hospitality",
    collar: "blue",
    salary: "UGX 2M – 4.5M/mo",
    posted: "12 hours ago",
    logo: "🟣",
    description: "Oversee kitchen operations, develop seasonal menus, and manage a team of 15 cooks for the 5-star hotel restaurant.",
    tags: ["Culinary", "Hotel", "Menu Planning"],
    applyUrl: "https://www.serenahotels.com/kampala/careers",
  },

  // === KENYA ===
  {
    id: "ke-1",
    title: "Product Manager – Mobile Payments",
    company: "Safaricom PLC",
    location: "Nairobi, Kenya",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "KES 350K – 600K/mo",
    posted: "3 hours ago",
    logo: "🟢",
    featured: true,
    description: "Lead M-Pesa product roadmap, drive feature prioritization, and manage cross-functional teams building next-gen payment solutions.",
    tags: ["Product Management", "Fintech", "M-Pesa"],
    applyUrl: "https://www.safaricom.co.ke/about/careers",
    requirements: ["5+ years product management", "Fintech experience preferred", "MBA or equivalent", "Agile methodology expertise"],
    benefits: ["Competitive salary", "M-Pesa wallet bonus", "Health & pension", "Stock options"],
  },
  {
    id: "ke-2",
    title: "Long-Haul Truck Driver",
    company: "Bollore Transport & Logistics",
    location: "Mombasa, Kenya",
    type: "Full-time",
    category: "Transportation",
    collar: "blue",
    salary: "KES 80K – 150K/mo",
    posted: "5 hours ago",
    logo: "🟠",
    description: "Drive cross-border transport routes (Mombasa–Kampala–Kigali corridor). Valid driving license BCE class required.",
    tags: ["CDL", "Cross-border", "East Africa"],
    applyUrl: "https://www.brightermonday.co.ke/jobs",
  },
  {
    id: "ke-3",
    title: "UX Designer",
    company: "Equity Bank Group",
    location: "Nairobi, Kenya",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "KES 200K – 400K/mo",
    posted: "1 day ago",
    logo: "🟡",
    remote: true,
    description: "Design intuitive mobile banking experiences for 17M+ customers across 6 African countries.",
    tags: ["Figma", "Mobile UX", "Banking"],
    applyUrl: "https://equitygroupholdings.com/ke/careers",
  },
  {
    id: "ke-4",
    title: "Security Guard – Corporate",
    company: "G4S Kenya",
    location: "Nairobi, Kenya",
    type: "Full-time",
    category: "Retail",
    collar: "blue",
    salary: "KES 25K – 40K/mo",
    posted: "8 hours ago",
    logo: "🔵",
    description: "Provide physical security for corporate offices. Must have valid Kenya Police Clearance Certificate.",
    tags: ["Security", "Corporate", "Licensed"],
    applyUrl: "https://www.g4s.com/en-ke/careers",
  },

  // === TANZANIA ===
  {
    id: "tz-1",
    title: "Warehouse Operations Manager",
    company: "DHL East Africa",
    location: "Dar es Salaam, Tanzania",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "TZS 3M – 5.5M/mo",
    posted: "1 day ago",
    logo: "🔴",
    description: "Oversee daily warehouse operations, manage team of 30+ associates, and optimize inventory management systems.",
    tags: ["Logistics", "Warehouse", "Inventory"],
    applyUrl: "https://www.dhl.com/tz-en/home/careers.html",
  },
  {
    id: "tz-2",
    title: "Mining Engineer",
    company: "Barrick Gold Tanzania",
    location: "Mwanza, Tanzania",
    type: "Full-time",
    category: "Engineering",
    collar: "white",
    salary: "TZS 8M – 15M/mo",
    posted: "2 days ago",
    logo: "🟡",
    featured: true,
    description: "Plan and supervise mining operations at North Mara Gold Mine. BSc Mining Engineering required.",
    tags: ["Mining", "Gold", "Operations"],
    applyUrl: "https://www.barrick.com/English/careers",
  },

  // === RWANDA ===
  {
    id: "rw-1",
    title: "Data Analyst",
    company: "Bank of Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Finance",
    collar: "white",
    salary: "RWF 800K – 1.5M/mo",
    posted: "10 hours ago",
    logo: "🟢",
    description: "Analyze banking data to drive business intelligence and support strategic decision-making for Rwanda's largest bank.",
    tags: ["SQL", "Power BI", "Banking"],
    applyUrl: "https://www.bk.rw/careers",
  },

  // === NIGERIA ===
  {
    id: "ng-1",
    title: "UI/UX Designer",
    company: "Flutterwave",
    location: "Lagos, Nigeria",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "NGN 800K – 1.5M/mo",
    posted: "7 hours ago",
    logo: "🟡",
    remote: true,
    description: "Create beautiful, user-centered designs for Africa's leading payment infrastructure company. Shape fintech products used by millions.",
    tags: ["Figma", "Design Systems", "Fintech"],
    applyUrl: "https://flutterwave.com/us/careers",
  },
  {
    id: "ng-2",
    title: "Petroleum Engineer",
    company: "Shell Nigeria",
    location: "Port Harcourt, Nigeria",
    type: "Full-time",
    category: "Engineering",
    collar: "white",
    salary: "NGN 2M – 4M/mo",
    posted: "2 days ago",
    logo: "🟠",
    description: "Optimize oil and gas extraction processes, manage well completion programs, and ensure environmental compliance.",
    tags: ["Oil & Gas", "Reservoir Engineering", "HSE"],
    applyUrl: "https://www.shell.com.ng/careers.html",
  },

  // === SOUTH AFRICA ===
  {
    id: "za-1",
    title: "DevOps Engineer",
    company: "Naspers / Prosus",
    location: "Cape Town, South Africa",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "ZAR 65K – 95K/mo",
    posted: "4 hours ago",
    logo: "🟣",
    remote: true,
    description: "Build and maintain CI/CD pipelines, manage Kubernetes clusters, and ensure 99.99% uptime for global e-commerce platforms.",
    tags: ["Kubernetes", "AWS", "Terraform"],
    applyUrl: "https://www.prosus.com/careers",
  },

  // === UAE ===
  {
    id: "ae-1",
    title: "HVAC Technician",
    company: "Emirates Cooling Systems",
    location: "Dubai, UAE",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "AED 5,000 – 9,000/mo",
    posted: "6 hours ago",
    logo: "🟠",
    description: "Install and service HVAC systems in commercial high-rise buildings across Dubai. EPA certification preferred.",
    tags: ["HVAC", "Installation", "Chiller Systems"],
    applyUrl: "https://www.bayt.com/en/uae/jobs/hvac-technician-jobs/",
  },
  {
    id: "ae-2",
    title: "Civil Engineer – Infrastructure",
    company: "Emaar Properties",
    location: "Dubai, UAE",
    type: "Full-time",
    category: "Engineering",
    collar: "white",
    salary: "AED 15K – 25K/mo",
    posted: "1 day ago",
    logo: "🟡",
    featured: true,
    description: "Lead infrastructure projects including roads, bridges, and utilities for Dubai's expanding urban developments.",
    tags: ["Civil Engineering", "AutoCAD", "Project Management"],
    applyUrl: "https://www.emaar.com/en/careers",
    requirements: ["BSc Civil Engineering", "5+ years infrastructure experience", "AutoCAD proficiency", "PMP certification preferred"],
    benefits: ["Tax-free salary", "Housing allowance", "Annual flights home", "Health insurance"],
  },
  {
    id: "ae-3",
    title: "Hotel Receptionist",
    company: "Jumeirah Group",
    location: "Abu Dhabi, UAE",
    type: "Full-time",
    category: "Hospitality",
    collar: "white",
    salary: "AED 4,000 – 6,000/mo",
    posted: "3 hours ago",
    logo: "🟣",
    description: "Provide world-class guest services at a 5-star luxury resort. Multilingual skills are a plus. Accommodation provided.",
    tags: ["Front Desk", "Hospitality", "Multilingual"],
    applyUrl: "https://www.jumeirah.com/en/careers",
  },
  {
    id: "ae-4",
    title: "Construction Foreman",
    company: "Al Habtoor Group",
    location: "Sharjah, UAE",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "AED 6,000 – 10,000/mo",
    posted: "8 hours ago",
    logo: "🔵",
    urgent: true,
    description: "Supervise construction crews on residential tower projects. Must have 5+ years experience and valid UAE trade license.",
    tags: ["Construction", "Supervision", "Residential"],
    applyUrl: "https://www.habtoorgroup.com/en/careers",
  },

  // === UNITED KINGDOM ===
  {
    id: "uk-1",
    title: "Data Scientist – Machine Learning",
    company: "Amazon Web Services",
    location: "London, UK",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "£65,000 – £95,000/yr",
    posted: "3 hours ago",
    logo: "🟢",
    featured: true,
    remote: true,
    description: "Design and deploy ML models at scale to drive business decisions across AWS services. PhD or MSc in relevant field preferred.",
    tags: ["Python", "Machine Learning", "TensorFlow"],
    applyUrl: "https://www.amazon.jobs/en-gb/",
    requirements: ["PhD/MSc in CS, Statistics, or related", "3+ years ML experience", "Python, TensorFlow/PyTorch", "Experience with large-scale data"],
    benefits: ["Relocation package", "Stock options", "Health & dental", "Learning budget"],
  },
  {
    id: "uk-2",
    title: "NHS Staff Nurse",
    company: "NHS England",
    location: "Manchester, UK",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "£28,000 – £36,000/yr",
    posted: "12 hours ago",
    logo: "🔵",
    urgent: true,
    description: "Provide patient care in acute medical wards. Band 5 position with career progression opportunities. NMC registration required.",
    tags: ["NMC Registered", "Acute Care", "Band 5"],
    applyUrl: "https://www.jobs.nhs.uk/",
  },
  {
    id: "uk-3",
    title: "Carpenter – Residential",
    company: "Barratt Developments",
    location: "Birmingham, UK",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "£30,000 – £42,000/yr",
    posted: "1 day ago",
    logo: "🟠",
    description: "Carry out first and second fix carpentry on new-build residential properties. CSCS card required.",
    tags: ["Carpentry", "CSCS", "New Build"],
    applyUrl: "https://www.barrattcareers.co.uk/",
  },

  // === GERMANY ===
  {
    id: "de-1",
    title: "Automotive Engineer",
    company: "BMW Group",
    location: "Munich, Germany",
    type: "Full-time",
    category: "Engineering",
    collar: "white",
    salary: "€55,000 – €80,000/yr",
    posted: "5 hours ago",
    logo: "🔵",
    description: "Design and test electric vehicle powertrain components. German language skills B2+ required.",
    tags: ["EV", "Powertrain", "CATIA"],
    applyUrl: "https://www.bmwgroup.jobs/",
  },

  // === CANADA ===
  {
    id: "ca-1",
    title: "Full Stack Developer",
    company: "Shopify",
    location: "Toronto, Canada",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "CAD $90K – $130K/yr",
    posted: "4 hours ago",
    logo: "🟢",
    featured: true,
    remote: true,
    description: "Build merchant-facing features for the world's leading e-commerce platform using Ruby on Rails and React.",
    tags: ["Ruby on Rails", "React", "GraphQL"],
    applyUrl: "https://www.shopify.com/careers",
    requirements: ["3+ years full-stack experience", "Ruby on Rails proficiency", "React/TypeScript", "GraphQL knowledge"],
    benefits: ["Remote-first culture", "Stock options", "Health & wellness", "$5K learning budget"],
  },
  {
    id: "ca-2",
    title: "Pipefitter – Oil Sands",
    company: "Suncor Energy",
    location: "Fort McMurray, Canada",
    type: "Contract",
    category: "Construction",
    collar: "blue",
    salary: "CAD $45 – $65/hr",
    posted: "1 day ago",
    logo: "🟠",
    urgent: true,
    description: "Install, assemble, and maintain piping systems in oil sands facilities. Red Seal certification required.",
    tags: ["Pipefitting", "Red Seal", "Oil Sands"],
    applyUrl: "https://www.suncor.com/en/careers",
  },
  {
    id: "ca-3",
    title: "Registered Nurse – Emergency",
    company: "Toronto General Hospital",
    location: "Toronto, Canada",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "CAD $75K – $95K/yr",
    posted: "6 hours ago",
    logo: "🟣",
    description: "Provide emergency nursing care in one of Canada's top teaching hospitals. CNO registration and BLS certification required.",
    tags: ["Emergency Nursing", "CNO", "BLS"],
    applyUrl: "https://www.uhn.ca/careers",
  },

  // === UNITED STATES ===
  {
    id: "us-1",
    title: "Senior Cloud Architect",
    company: "Google",
    location: "Mountain View, CA, USA",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "$180K – $260K/yr",
    posted: "1 hour ago",
    logo: "🟢",
    featured: true,
    remote: true,
    description: "Design multi-cloud architectures for enterprise customers. Lead technical solution design for Fortune 500 companies.",
    tags: ["GCP", "Cloud Architecture", "Enterprise"],
    applyUrl: "https://careers.google.com/",
    requirements: ["8+ years cloud architecture", "GCP/AWS/Azure certifications", "Enterprise consulting experience", "Strong presentation skills"],
    benefits: ["Top-tier compensation", "RSUs", "Free meals & gym", "20% time projects"],
  },
  {
    id: "us-2",
    title: "Electrician – Master",
    company: "IBEW Local 3",
    location: "New York, NY, USA",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "$85K – $120K/yr",
    posted: "3 hours ago",
    logo: "🔵",
    description: "Perform electrical installations in commercial and residential buildings across NYC. NYS Master Electrician license required.",
    tags: ["Master Electrician", "NEC Code", "Commercial"],
    applyUrl: "https://www.ibew3.org/jobs",
  },
  {
    id: "us-3",
    title: "Physician Assistant",
    company: "Mayo Clinic",
    location: "Rochester, MN, USA",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "$115K – $145K/yr",
    posted: "8 hours ago",
    logo: "🟣",
    description: "Provide patient care alongside physicians in internal medicine. PA-C certification and state licensure required.",
    tags: ["PA-C", "Internal Medicine", "Clinical"],
    applyUrl: "https://jobs.mayoclinic.org/",
  },
  {
    id: "us-4",
    title: "CDL Truck Driver – Regional",
    company: "FedEx Freight",
    location: "Dallas, TX, USA",
    type: "Full-time",
    category: "Transportation",
    collar: "blue",
    salary: "$65K – $85K/yr",
    posted: "5 hours ago",
    logo: "🟠",
    description: "Regional LTL freight delivery across Texas, Oklahoma, and Louisiana. Home most weekends. CDL-A required.",
    tags: ["CDL-A", "LTL Freight", "Regional"],
    applyUrl: "https://careers.fedex.com/freight",
  },
  {
    id: "us-5",
    title: "Investment Banking Analyst",
    company: "Goldman Sachs",
    location: "New York, NY, USA",
    type: "Full-time",
    category: "Finance",
    collar: "white",
    salary: "$110K – $150K/yr + bonus",
    posted: "2 days ago",
    logo: "🟡",
    featured: true,
    description: "Support M&A transactions, build financial models, and prepare pitch materials for Fortune 500 deals.",
    tags: ["M&A", "Financial Modeling", "DCF"],
    applyUrl: "https://www.goldmansachs.com/careers/",
  },
  {
    id: "us-6",
    title: "HVAC Installer",
    company: "Carrier Global",
    location: "Atlanta, GA, USA",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "$50K – $72K/yr",
    posted: "1 day ago",
    logo: "🔴",
    description: "Install residential and light commercial HVAC systems. EPA Section 608 certification required.",
    tags: ["HVAC", "EPA Certified", "Residential"],
    applyUrl: "https://www.corporate.carrier.com/careers/",
  },
  {
    id: "us-7",
    title: "Marketing Director",
    company: "Nike Inc.",
    location: "Portland, OR, USA",
    type: "Full-time",
    category: "Marketing",
    collar: "white",
    salary: "$140K – $200K/yr",
    posted: "4 hours ago",
    logo: "🟣",
    description: "Lead integrated marketing campaigns for Nike's North American running category. 8+ years experience required.",
    tags: ["Brand Marketing", "Campaign Strategy", "D2C"],
    applyUrl: "https://jobs.nike.com/",
  },

  // === ETHIOPIA ===
  {
    id: "et-1",
    title: "Textile Factory Supervisor",
    company: "Hawassa Industrial Park",
    location: "Hawassa, Ethiopia",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "ETB 25K – 45K/mo",
    posted: "1 day ago",
    logo: "🔴",
    description: "Supervise garment production lines, ensure quality standards, and manage shift schedules for 100+ workers.",
    tags: ["Textile", "Production", "Quality Control"],
    applyUrl: "https://www.ethiojobs.net/",
  },

  // === GHANA ===
  {
    id: "gh-1",
    title: "Mobile Developer – Android",
    company: "MTN Ghana",
    location: "Accra, Ghana",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "GHS 8K – 15K/mo",
    posted: "9 hours ago",
    logo: "🟡",
    remote: true,
    description: "Build and maintain Android applications for MTN's 25M+ subscriber base. Kotlin/Java experience required.",
    tags: ["Android", "Kotlin", "Mobile"],
    applyUrl: "https://www.mtn.com.gh/careers",
  },

  // === MORE UGANDA JOBS ===
  {
    id: "ug-11",
    title: "Secondary School Teacher – Mathematics",
    company: "Kampala International School",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Education",
    collar: "white",
    salary: "UGX 2M – 4M/mo",
    posted: "2 days ago",
    logo: "🟢",
    description: "Teach mathematics to secondary students (S1-S6) following the Cambridge International curriculum.",
    tags: ["Teaching", "Mathematics", "Cambridge"],
    applyUrl: "https://www.brightermonday.co.ug/jobs",
  },
  {
    id: "ug-12",
    title: "Mechanic – Diesel Engines",
    company: "Uganda Breweries Limited",
    location: "Port Bell, Uganda",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "UGX 1.8M – 3.5M/mo",
    posted: "3 days ago",
    logo: "🔴",
    description: "Maintain and repair diesel engines for brewery fleet vehicles and generator systems.",
    tags: ["Diesel Mechanic", "Fleet", "Generators"],
    applyUrl: "https://www.diageo.com/en/careers",
  },
  {
    id: "ug-13",
    title: "Pharmacist",
    company: "Cipla Quality Chemical Industries",
    location: "Luzira, Kampala, Uganda",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "UGX 4M – 7M/mo",
    posted: "1 day ago",
    logo: "🟣",
    description: "Oversee pharmaceutical manufacturing quality assurance and regulatory compliance for ARV production.",
    tags: ["Pharmacy", "GMP", "Quality Assurance"],
    applyUrl: "https://www.cipla.co.ug/careers",
  },
  {
    id: "ug-14",
    title: "Agricultural Extension Officer",
    company: "Uganda Coffee Development Authority",
    location: "Mbale, Uganda",
    type: "Full-time",
    category: "Education",
    collar: "white",
    salary: "UGX 1.5M – 3M/mo",
    posted: "4 days ago",
    logo: "🟢",
    description: "Train smallholder coffee farmers on best practices, pest management, and post-harvest handling techniques.",
    tags: ["Agriculture", "Coffee", "Extension"],
    applyUrl: "https://www.ucda.go.ug/careers",
  },
  {
    id: "ug-15",
    title: "Boda Boda Rider – Delivery",
    company: "SafeBoda",
    location: "Kampala, Uganda",
    type: "Freelance",
    category: "Transportation",
    collar: "blue",
    salary: "UGX 800K – 2M/mo",
    posted: "1 hour ago",
    logo: "🟠",
    description: "Deliver food and packages across Kampala using the SafeBoda app. Must own a motorcycle and have a valid permit.",
    tags: ["Delivery", "Motorcycle", "Flexible Hours"],
    applyUrl: "https://safeboda.com/ug/",
  },

  // === MORE INTERNATIONAL ===
  {
    id: "fr-1",
    title: "Fashion Designer – Haute Couture",
    company: "LVMH Group",
    location: "Paris, France",
    type: "Full-time",
    category: "Retail",
    collar: "white",
    salary: "€45,000 – €70,000/yr",
    posted: "2 days ago",
    logo: "🟣",
    description: "Design seasonal collections for luxury fashion houses under the LVMH umbrella. Fashion degree and portfolio required.",
    tags: ["Fashion Design", "Luxury", "Couture"],
    applyUrl: "https://www.lvmh.com/join-us/",
  },
  {
    id: "sg-1",
    title: "Cybersecurity Analyst",
    company: "DBS Bank",
    location: "Singapore",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "SGD 6K – 10K/mo",
    posted: "6 hours ago",
    logo: "🔵",
    description: "Monitor and respond to security threats, conduct vulnerability assessments, and implement security controls.",
    tags: ["SIEM", "Incident Response", "CISSP"],
    applyUrl: "https://www.dbs.com/careers/",
  },
  {
    id: "au-1",
    title: "Diesel Fitter – Mining",
    company: "BHP",
    location: "Perth, Australia",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "AUD $90K – $130K/yr",
    posted: "1 day ago",
    logo: "🟠",
    urgent: true,
    description: "Maintain and repair heavy mining equipment including haul trucks and excavators. FIFO roster: 2 weeks on, 1 week off.",
    tags: ["Mining", "Diesel", "FIFO"],
    applyUrl: "https://www.bhp.com/careers",
  },
  {
    id: "us-8",
    title: "Dental Hygienist",
    company: "Aspen Dental",
    location: "Chicago, IL, USA",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "$72K – $90K/yr",
    posted: "3 hours ago",
    logo: "🟢",
    description: "Provide preventive dental care including cleanings, X-rays, and patient education. RDH license required.",
    tags: ["Dental", "RDH", "Preventive Care"],
    applyUrl: "https://careers.aspendental.com/",
  },
  {
    id: "us-9",
    title: "Warehouse Associate",
    company: "Amazon Fulfillment",
    location: "Houston, TX, USA",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "$17 – $22/hr",
    posted: "2 hours ago",
    logo: "🟠",
    description: "Pick, pack, and ship customer orders in a fast-paced fulfillment center. Shifts available including overnight.",
    tags: ["Warehouse", "Fulfillment", "Flexible Shifts"],
    applyUrl: "https://www.amazon.jobs/",
  },
  {
    id: "ke-5",
    title: "Digital Marketing Specialist",
    company: "Jumia Kenya",
    location: "Nairobi, Kenya",
    type: "Full-time",
    category: "Marketing",
    collar: "white",
    salary: "KES 120K – 220K/mo",
    posted: "10 hours ago",
    logo: "🟡",
    description: "Drive customer acquisition through SEO, SEM, social media, and email marketing for East Africa's largest e-commerce platform.",
    tags: ["SEO", "Google Ads", "E-commerce"],
    applyUrl: "https://group.jumia.com/careers",
  },
  {
    id: "ug-16",
    title: "Legal Counsel – Corporate",
    company: "Bowmans Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Legal",
    collar: "white",
    salary: "UGX 7M – 14M/mo",
    posted: "3 days ago",
    logo: "🟣",
    description: "Provide legal advisory on corporate transactions, mergers, and regulatory compliance across East African markets.",
    tags: ["Corporate Law", "M&A", "Compliance"],
    applyUrl: "https://www.bowmanslaw.com/careers/",
  },
  {
    id: "ug-17",
    title: "Painter – Commercial",
    company: "Kansai Plascon Uganda",
    location: "Kampala, Uganda",
    type: "Contract",
    category: "Construction",
    collar: "blue",
    salary: "UGX 800K – 1.5M/mo",
    posted: "2 days ago",
    logo: "🔵",
    description: "Apply interior and exterior paint finishes on commercial buildings. Experience with spray equipment preferred.",
    tags: ["Painting", "Commercial", "Spray Equipment"],
    applyUrl: "https://www.kansaiplascon.com/careers",
  },
  {
    id: "ae-5",
    title: "Retail Store Manager",
    company: "Majid Al Futtaim",
    location: "Dubai Mall, UAE",
    type: "Full-time",
    category: "Retail",
    collar: "white",
    salary: "AED 12K – 18K/mo",
    posted: "4 hours ago",
    logo: "🟡",
    description: "Manage daily store operations, lead sales team, and achieve revenue targets for a flagship retail outlet.",
    tags: ["Retail Management", "Sales", "KPIs"],
    applyUrl: "https://www.majidalfuttaim.com/en/careers",
  },
];

export const topCompanies = [
  { name: "Andela Uganda", industry: "Technology", jobs: 145, logo: "🟣" },
  { name: "Mulago Hospital", industry: "Healthcare", jobs: 89, logo: "🟢" },
  { name: "Umeme Limited", industry: "Energy", jobs: 67, logo: "🔵" },
  { name: "Safaricom PLC", industry: "Telecoms", jobs: 52, logo: "🟡" },
  { name: "Stanbic Bank", industry: "Finance", jobs: 43, logo: "🟠" },
  { name: "DHL East Africa", industry: "Logistics", jobs: 38, logo: "🔴" },
];

export const stats = [
  { label: "Free Job Listings", value: "24,500+", icon: "📋" },
  { label: "Companies", value: "8,200+", icon: "🏢" },
  { label: "Countries Covered", value: "50+", icon: "🌍" },
  { label: "Successful Placements", value: "1.5M+", icon: "✅" },
];
