export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  type: "Full-time" | "Part-time" | "Contract" | "Freelance" | "Internship";
  category: string;
  collar: "white" | "blue";
  salary: string;
  posted: string;
  logo: string;
  featured?: boolean;
  remote?: boolean;
  urgent?: boolean;
  description: string;
  tags: string[];
}

export const jobCategories = [
  { name: "Technology", icon: "💻", count: 2840, color: "primary" },
  { name: "Healthcare", icon: "🏥", count: 1920, color: "accent" },
  { name: "Finance", icon: "💰", count: 1560, color: "highlight" },
  { name: "Construction", icon: "🏗️", count: 1340, color: "primary" },
  { name: "Education", icon: "📚", count: 980, color: "accent" },
  { name: "Marketing", icon: "📢", count: 870, color: "highlight" },
  { name: "Manufacturing", icon: "🏭", count: 760, color: "primary" },
  { name: "Transportation", icon: "🚛", count: 650, color: "accent" },
  { name: "Hospitality", icon: "🏨", count: 590, color: "highlight" },
  { name: "Retail", icon: "🛒", count: 1200, color: "primary" },
  { name: "Engineering", icon: "⚙️", count: 1100, color: "accent" },
  { name: "Legal", icon: "⚖️", count: 430, color: "highlight" },
];

export const featuredJobs: Job[] = [
  {
    id: "1",
    title: "Senior React Developer",
    company: "Andela Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "UGX 8M – 15M/mo",
    posted: "2 hours ago",
    logo: "🟣",
    featured: true,
    remote: true,
    description: "Build cutting-edge web applications using React, TypeScript, and modern tooling.",
    tags: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "2",
    title: "Electrician – Commercial",
    company: "Umeme Limited",
    location: "Jinja, Uganda",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "UGX 1.5M – 3M/mo",
    posted: "4 hours ago",
    logo: "🔵",
    urgent: true,
    description: "Install, maintain, and repair electrical systems in commercial buildings.",
    tags: ["Electrical", "Commercial", "Licensed"],
  },
  {
    id: "3",
    title: "Product Manager",
    company: "Safaricom PLC",
    location: "Nairobi, Kenya",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "KES 350K – 600K/mo",
    posted: "6 hours ago",
    logo: "🟢",
    featured: true,
    description: "Lead product strategy and roadmap for a growing mobile platform.",
    tags: ["Product", "Strategy", "Fintech"],
  },
  {
    id: "4",
    title: "HVAC Technician",
    company: "Emirates Cooling Systems",
    location: "Dubai, UAE",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "AED 5K – 9K/mo",
    posted: "8 hours ago",
    logo: "🟠",
    description: "Install and service heating, ventilation, and air conditioning systems.",
    tags: ["HVAC", "Installation", "Maintenance"],
  },
  {
    id: "5",
    title: "UX/UI Designer",
    company: "Flutterwave",
    location: "Lagos, Nigeria",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "NGN 800K – 1.5M/mo",
    posted: "12 hours ago",
    logo: "🟡",
    remote: true,
    description: "Create beautiful, user-centered designs for web and mobile applications.",
    tags: ["Figma", "UI Design", "Prototyping"],
  },
  {
    id: "6",
    title: "Warehouse Supervisor",
    company: "DHL East Africa",
    location: "Dar es Salaam, Tanzania",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "TZS 2M – 3.5M/mo",
    posted: "1 day ago",
    logo: "🔴",
    description: "Oversee daily warehouse operations, manage team of 20+ associates.",
    tags: ["Logistics", "Management", "Inventory"],
  },
  {
    id: "7",
    title: "Registered Nurse",
    company: "Mulago National Hospital",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Healthcare",
    collar: "white",
    salary: "UGX 2M – 4.5M/mo",
    posted: "1 day ago",
    logo: "🟣",
    urgent: true,
    description: "Provide patient care in a fast-paced hospital environment.",
    tags: ["Nursing", "Patient Care", "BSN"],
  },
  {
    id: "8",
    title: "Plumber – Residential",
    company: "National Water & Sewerage",
    location: "Entebbe, Uganda",
    type: "Full-time",
    category: "Construction",
    collar: "blue",
    salary: "UGX 1.2M – 2.5M/mo",
    posted: "2 days ago",
    logo: "🔵",
    description: "Handle residential plumbing installations, repairs, and maintenance.",
    tags: ["Plumbing", "Residential", "Licensed"],
  },
  {
    id: "9",
    title: "Data Scientist",
    company: "Amazon Web Services",
    location: "London, UK",
    type: "Full-time",
    category: "Technology",
    collar: "white",
    salary: "£65K – £95K/yr",
    posted: "3 hours ago",
    logo: "🟢",
    featured: true,
    remote: true,
    description: "Analyze large datasets and build ML models to drive business decisions.",
    tags: ["Python", "Machine Learning", "SQL"],
  },
  {
    id: "10",
    title: "Long-Haul Truck Driver",
    company: "Bollore Transport & Logistics",
    location: "Mombasa, Kenya",
    type: "Full-time",
    category: "Transportation",
    collar: "blue",
    salary: "KES 80K – 150K/mo",
    posted: "5 hours ago",
    logo: "🟠",
    description: "Cross-border transport routes across East Africa with competitive pay.",
    tags: ["CDL", "Cross-border", "East Africa"],
  },
  {
    id: "11",
    title: "Financial Analyst",
    company: "Stanbic Bank Uganda",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Finance",
    collar: "white",
    salary: "UGX 5M – 9M/mo",
    posted: "1 day ago",
    logo: "🟡",
    description: "Perform financial modeling and analysis for investment decisions.",
    tags: ["Finance", "Modeling", "Excel"],
  },
  {
    id: "12",
    title: "Welder – MIG/TIG",
    company: "Roofings Group",
    location: "Kampala, Uganda",
    type: "Full-time",
    category: "Manufacturing",
    collar: "blue",
    salary: "UGX 1.5M – 3M/mo",
    posted: "2 days ago",
    logo: "🔴",
    urgent: true,
    description: "Perform MIG and TIG welding on structural steel and fabrication projects.",
    tags: ["Welding", "MIG", "TIG"],
  },
];

export const topCompanies = [
  { name: "TechVault Inc.", industry: "Technology", jobs: 145, logo: "🟣" },
  { name: "Metro Health Center", industry: "Healthcare", jobs: 89, logo: "🟢" },
  { name: "PowerGrid Solutions", industry: "Construction", jobs: 67, logo: "🔵" },
  { name: "DataPulse Analytics", industry: "Analytics", jobs: 52, logo: "🟡" },
  { name: "Goldman & Pierce", industry: "Finance", jobs: 43, logo: "🟠" },
  { name: "LogiFlow Corp", industry: "Logistics", jobs: 38, logo: "🔴" },
];

export const stats = [
  { label: "Active Jobs", value: "24,500+", icon: "📋" },
  { label: "Companies", value: "8,200+", icon: "🏢" },
  { label: "Job Seekers", value: "3.2M+", icon: "👥" },
  { label: "Placements", value: "1.5M+", icon: "✅" },
];
